Vagrant.configure("2") do |config|
  config.vm.define "eventstore" do |eventstore|
    eventstore.vm.box = "bento/ubuntu-16.04"
    eventstore.vm.network "forwarded_port", guest: 2113, host: 2113
    eventstore.vm.provision "ansible_local" do |ansible|
      ansible.become = true
      ansible.playbook = "playbook.yml"
      ansible.galaxy_role_file = "requirements.yml"
      ansible.galaxy_roles_path = "/etc/ansible/roles"
      ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end
  end
end