Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "172.17.177.21"
    node1.vm.network "forwarded_port", guest: 2113, host: 2113
  end
  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "172.17.177.22"
    node2.vm.network "forwarded_port", guest: 2113, host: 2113
  end
  config.vm.define "node3" do |node3|
    node3.vm.network "private_network", ip: "172.17.177.23"
  end
  config.vm.define 'controller' do |controller|
    controller.vm.network "private_network", ip: "172.17.177.11"
    controller.vm.provision "ansible_local" do |ansible|
      ansible.become            = true
      ansible.install           = true
      ansible.limit             = "nodes"
      ansible.playbook          = "playbook.yml"
      ansible.inventory_path    = "inventory.yml"
      ansible.galaxy_role_file  = "requirements.yml"
      ansible.galaxy_roles_path = "/etc/ansible/roles"
      ansible.galaxy_command    = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end
  end
end